### ISSUE TITLE
ModuleNotFoundError: No module named '# django'

### ISSUE THREAD

**Issue by piwel** [Cour-des-comptes/open-anafi-backend#2]
Bonjour

En lançant `docker-compose up`, j'obtiens l'erreur suivante :

```
open-anafi-backend % docker-compose up   
Creating network "open-anafi-backend_default" with the default driver
Creating code ... done
Attaching to code
code   | Starting RabbitMQ Messaging Server: rabbitmq-serverFAILED - check /var/log/rabbitmq/startup_\{log, _err\} ... (warning).
code   |  failed!
code   | Traceback (most recent call last):
code   |   File "/usr/local/lib/python3.6/site-packages/django/db/utils.py", line 110, in load_backend
code   |     return import_module('%s.base' % backend_name)
code   |   File "/usr/local/lib/python3.6/importlib/__init__.py", line 126, in import_module
code   |     return _bootstrap._gcd_import(name[level:], package, level)
code   |   File "<frozen importlib._bootstrap>", line 994, in _gcd_import
code   |   File "<frozen importlib._bootstrap>", line 971, in _find_and_load
code   |   File "<frozen importlib._bootstrap>", line 941, in _find_and_load_unlocked
code   |   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
code   |   File "<frozen importlib._bootstrap>", line 994, in _gcd_import
code   |   File "<frozen importlib._bootstrap>", line 971, in _find_and_load
code   |   File "<frozen importlib._bootstrap>", line 941, in _find_and_load_unlocked
code   |   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
code   |   File "<frozen importlib._bootstrap>", line 994, in _gcd_import
code   |   File "<frozen importlib._bootstrap>", line 971, in _find_and_load
code   |   File "<frozen importlib._bootstrap>", line 941, in _find_and_load_unlocked
code   |   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
code   |   File "<frozen importlib._bootstrap>", line 994, in _gcd_import
code   |   File "<frozen importlib._bootstrap>", line 971, in _find_and_load
code   |   File "<frozen importlib._bootstrap>", line 941, in _find_and_load_unlocked
code   |   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
code   |   File "<frozen importlib._bootstrap>", line 994, in _gcd_import
code   |   File "<frozen importlib._bootstrap>", line 971, in _find_and_load
code   |   File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
code   | ModuleNotFoundError: No module named '# django'
code   | 
code   | The above exception was the direct cause of the following exception:
code   | 
code   | Traceback (most recent call last):
code   |   File "manage.py", line 15, in <module>
code   |     execute_from_command_line(sys.argv)
code   |   File "/usr/local/lib/python3.6/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
code   |     utility.execute()
code   |   File "/usr/local/lib/python3.6/site-packages/django/core/management/__init__.py", line 375, in execute
code   |     self.fetch_command(subcommand).run_from_argv(self.argv)
code   |   File "/usr/local/lib/python3.6/site-packages/django/core/management/base.py", line 323, in run_from_argv
code   |     self.execute(*args, **cmd_options)
code   |   File "/usr/local/lib/python3.6/site-packages/django/core/management/base.py", line 361, in execute
code   |     self.check()
code   |   File "/usr/local/lib/python3.6/site-packages/django/core/management/base.py", line 390, in check
code   |     include_deployment_checks=include_deployment_checks,
code   |   File "/usr/local/lib/python3.6/site-packages/django/core/management/commands/migrate.py", line 64, in _run_checks
code   |     issues = run_checks(tags=[Tags.database])
code   |   File "/usr/local/lib/python3.6/site-packages/django/core/checks/registry.py", line 72, in run_checks
code   |     new_errors = check(app_configs=app_configs)
code   |   File "/usr/local/lib/python3.6/site-packages/django/core/checks/database.py", line 9, in check_database_backends
code   |     for conn in connections.all():
code   |   File "/usr/local/lib/python3.6/site-packages/django/db/utils.py", line 216, in all
code   |     return [self[alias] for alias in self]
code   |   File "/usr/local/lib/python3.6/site-packages/django/db/utils.py", line 216, in <listcomp>
code   |     return [self[alias] for alias in self]
code   |   File "/usr/local/lib/python3.6/site-packages/django/db/utils.py", line 201, in __getitem__
code   |     backend = load_backend(db['ENGINE'])
code   |   File "/usr/local/lib/python3.6/site-packages/django/db/utils.py", line 125, in load_backend
code   |     ) from e_user
code   | django.core.exceptions.ImproperlyConfigured: '# django.db.backends.postgresql_psycopg2' isn't an available database backend.
code   | Try using 'django.db.backends.XXX', where XXX is one of:
code   |     'mysql', 'oracle', 'postgresql', 'sqlite3'
code   | Traceback (most recent call last):
code   |   File "/usr/local/lib/python3.6/site-packages/django/db/utils.py", line 110, in load_backend
code   |     return import_module('%s.base' % backend_name)
code   |   File "/usr/local/lib/python3.6/importlib/__init__.py", line 126, in import_module
code   |     return _bootstrap._gcd_import(name[level:], package, level)
code   |   File "<frozen importlib._bootstrap>", line 994, in _gcd_import
code   |   File "<frozen importlib._bootstrap>", line 971, in _find_and_load
code   |   File "<frozen importlib._bootstrap>", line 941, in _find_and_load_unlocked
code   |   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
code   |   File "<frozen importlib._bootstrap>", line 994, in _gcd_import
code   |   File "<frozen importlib._bootstrap>", line 971, in _find_and_load
code   |   File "<frozen importlib._bootstrap>", line 941, in _find_and_load_unlocked
code   |   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
code   |   File "<frozen importlib._bootstrap>", line 994, in _gcd_import
code   |   File "<frozen importlib._bootstrap>", line 971, in _find_and_load
code   |   File "<frozen importlib._bootstrap>", line 941, in _find_and_load_unlocked
code   |   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
code   |   File "<frozen importlib._bootstrap>", line 994, in _gcd_import
code   |   File "<frozen importlib._bootstrap>", line 971, in _find_and_load
code   |   File "<frozen importlib._bootstrap>", line 941, in _find_and_load_unlocked
code   |   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
code   |   File "<frozen importlib._bootstrap>", line 994, in _gcd_import
code   |   File "<frozen importlib._bootstrap>", line 971, in _find_and_load
code   |   File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
code   | ModuleNotFoundError: No module named '# django'
code   | 
code   | The above exception was the direct cause of the following exception:
code   | 
code   | Traceback (most recent call last):
code   |   File "manage.py", line 15, in <module>
code   |     execute_from_command_line(sys.argv)
code   |   File "/usr/local/lib/python3.6/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
code   |     utility.execute()
code   |   File "/usr/local/lib/python3.6/site-packages/django/core/management/__init__.py", line 375, in execute
code   |     self.fetch_command(subcommand).run_from_argv(self.argv)
code   |   File "/usr/local/lib/python3.6/site-packages/django/core/management/base.py", line 323, in run_from_argv
code   |     self.execute(*args, **cmd_options)
code   |   File "/usr/local/lib/python3.6/site-packages/django/core/management/base.py", line 361, in execute
code   |     self.check()
code   |   File "/usr/local/lib/python3.6/site-packages/django/core/management/base.py", line 390, in check
code   |     include_deployment_checks=include_deployment_checks,
code   |   File "/usr/local/lib/python3.6/site-packages/django/core/management/base.py", line 377, in _run_checks
code   |     return checks.run_checks(**kwargs)
code   |   File "/usr/local/lib/python3.6/site-packages/django/core/checks/registry.py", line 72, in run_checks
code   |     new_errors = check(app_configs=app_configs)
code   |   File "/usr/local/lib/python3.6/site-packages/django/core/checks/model_checks.py", line 32, in check_all_models
code   |     errors.extend(model.check(**kwargs))
code   |   File "/usr/local/lib/python3.6/site-packages/django/db/models/base.py", line 1237, in check
code   |     *cls._check_long_column_names(),
code   |   File "/usr/local/lib/python3.6/site-packages/django/db/models/base.py", line 1698, in _check_long_column_names
code   |     connection = connections[db]
code   |   File "/usr/local/lib/python3.6/site-packages/django/db/utils.py", line 201, in __getitem__
code   |     backend = load_backend(db['ENGINE'])
code   |   File "/usr/local/lib/python3.6/site-packages/django/db/utils.py", line 125, in load_backend
code   |     ) from e_user
code   | django.core.exceptions.ImproperlyConfigured: '# django.db.backends.postgresql_psycopg2' isn't an available database backend.
code   | Try using 'django.db.backends.XXX', where XXX is one of:
code   |     'mysql', 'oracle', 'postgresql', 'sqlite3'
code   | Error: unable to perform an operation on node 'rabbit@e00ea4c4da49'. Please see diagnostics information and suggestions below.
code   | 
code   | Most common reasons for this are:
code   | 
code   |  * Target node is unreachable (e.g. due to hostname resolution, TCP connection or firewall issues)
code   |  * CLI tool fails to authenticate with the server (e.g. due to CLI tool's Erlang cookie not matching that of the server)
code   |  * Target node is not running
code   | 
code   | In addition to the diagnostics info below:
code   | 
code   |  * See the CLI, clustering and networking guides on http://rabbitmq.com/documentation.html to learn more
code   |  * Consult server logs on node rabbit@e00ea4c4da49
code   | 
code   | DIAGNOSTICS
code   | ===========
code   | 
code   | attempted to contact: [rabbit@e00ea4c4da49]
code   | 
code   | rabbit@e00ea4c4da49:
code   |   * connected to epmd (port 4369) on e00ea4c4da49
code   |   * epmd reports: node 'rabbit' not running at all
code   |                   no other nodes on e00ea4c4da49
code   |   * suggestion: start the node
code   | 
code   | Current node details:
code   |  * node name: rabbitmqcli4@e00ea4c4da49
code   |  * effective user's home directory: /var/lib/rabbitmq
code   |  * Erlang cookie hash: likmw0m0HT9kJkY0E7ufnw==
code   | 
code   | Error: unable to perform an operation on node 'rabbit@e00ea4c4da49'. Please see diagnostics information and suggestions below.
code   | 
code   | Most common reasons for this are:
code   | 
code   |  * Target node is unreachable (e.g. due to hostname resolution, TCP connection or firewall issues)
code   |  * CLI tool fails to authenticate with the server (e.g. due to CLI tool's Erlang cookie not matching that of the server)
code   |  * Target node is not running
code   | 
code   | In addition to the diagnostics info below:
code   | 
code   |  * See the CLI, clustering and networking guides on http://rabbitmq.com/documentation.html to learn more
code   |  * Consult server logs on node rabbit@e00ea4c4da49

```

Une idée de ce que je pourrais changer pour y remédier ?

Merci par avance

PiwEL

**Comment by salamsami** [comment]
Bonjour PiwEL , il est nécessaire de recréer la base de donnée DATABASE_CCI à partir des fichiers contenus dans dump_bdd et de configurer le fichier local_config.ini de manière à pouvoir y accéder.

Je pense que votre problème vient du fait que dans le local_config.ini que vous utilisez, vous avez gardez les champs de configuration de cette base de donnée tel quel :

[DATABASE_CCI]
ENGINE = # django.db.backends.postgresql_psycopg2
NAME = #
USER = #
PASSWORD = #
HOST = #
PORT = # 5432

Cette base est nécessaire au fonctionnement de l'application, il faut donc la recréer et renseigner les informations de configuration en place des commentaires.

**Comment by piwel** [comment]
Bonjour. Je vous remercie pour votre réponse. Je pensais que le container Docker aurait installé l’ensemble des dépendances y compris la base de données. 

En effet, j’ai laissé intacte la configuration. 

Comment recréer cette base ? Y a t’il un script d’installation ? Le moteur doit-il nécessairement être Django ?

**Comment by ArthV** [comment]
Bonjour Piwel,

Les explications pour recréer la base de données sont dans le [README](https://github.com/Cour-des-comptes/open-anafi-backend/blob/master/README.md#cr%C3%A9er-une-base--de-test-du-flux-cci). Il y a plusieurs script SQL qui te permette de reformer la base avec un jeu de donnée test . 

Aussi, j'attire ton attention sur le fait que la base est incomplète et je t'invite à aller chercher les données disponibles en open data par la DGFIP pour recréer complètement la base.

Bon courage à toi, 

Art'
